BBBBBBB BBBBBBBB BBBBBBB
 XXXX XXXX XX XXXX XX XXXXXXXXXXXXXXX
 XXXXXXXXX XXX XXXX XXXXXXXXXX XXXXX XXXXX XXXX XXXXXXXXX XXXXX XXX

 XXXXXXXXXXXXXXX XX XXXX XXXXXXXXX XXX XXX XXXXXXXXXXXX XX XXXXXX XXXXXX
 XX XXXXX XXX XXXXX XX XXX XXX XXXXXX XXXXXXX XXXXXX XXXXXXX XX
 XXXXXXXXX XX XXX XXXX XXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXX X XX XXX
 XXXXXXXX XX XXX XXXX XXXXXXX XXX XXXXX XXXXXXXX

 XXXXXXXXXXXXXXX XX XXXXXXXXXXX XX XXX XXXX XXXX XX XXXX XX XXXXXXX
 XXX XXXXXXX XXX XXXXXXXXX XXXXXXX XXXX XXX XXXXXXX XXXXXXXX XX
 XXXXXXXXXXXXXXX XX XXXXXXX XXX X XXXXXXXXXX XXXXXXXX  XXX XXX
 XXX XXXXXX XXXXXXX XXXXXX XXXXXXX XXX XXXX XXXXXXXX

 XXX XXXXXX XXXX XXXXXXXX X XXXX XX XXX XXX XXXXXX XXXXXXX XXXXXX XXXXXXX
 XXXXX XXXX XXXXXXXXXXXXXXXX  XX XXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 BBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
            XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBB
                    BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                        XXX XXXXXXXXXXXXXXX XXXXXX
                            BB BBBBBBBBBBBBBBBBBBBBBBBB B B
                                
                                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
                                    XX XXXXXXXXXX XXXXXXX XXXXXXXXXX
                                     gettext(u'Account') 
                                    XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                XXXX
                            BBBB
                                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
                                    XX XXXXXXXXXX XXXXXXX XXXXXXXXXX
                                     gettext(u'Account') 
                                XXXX
                            BBBBB
                        XXXXX
                        BB BBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                            XXX XXXXXXXXXXXXXXX XXXXXX
                                XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX
                                     gettext(u'Dashboard') 
                                XXXX
                            XXXXX
                        BBBBB
                        XXX XXXXXXXXXXXXXXX XXXXXX
                            XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                                 gettext(u'Logout') 
                            XXXX
                        XXXXX
                    BBBBBBBB
                BBBB
                    XXX XXXXXXXXXXXXXXX XXXXXX
                        XX XXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
                             gettext(u'Login or register') 
                        XXXX
                    XXXXX
                BBBBB
            XXXXX            
        XXXXXX
    XXXXXX
XXXXXX