BBBBBBB BBBBBBBB BBBBBBB
 XXXX XXXX XX XXXX XX XXXXXXXXXXXXXXX
 XXXXXXXXX XXX XXXX XXXXXXXXXX XXXXX XXXXX XXXX XXXXXXXXX XXXXX XXX

 XXXXXXXXXXXXXXX XX XXXX XXXXXXXXX XXX XXX XXXXXXXXXXXX XX XXXXXX XXXXXX
 XX XXXXX XXX XXXXX XX XXX XXX XXXXXX XXXXXXX XXXXXX XXXXXXX XX
 XXXXXXXXX XX XXX XXXX XXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXX X XX XXX
 XXXXXXXX XX XXX XXXX XXXXXXX XXX XXXXX XXXXXXXX

 XXXXXXXXXXXXXXX XX XXXXXXXXXXX XX XXX XXXX XXXX XX XXXX XX XXXXXXX
 XXX XXXXXXX XXX XXXXXXXXX XXXXXXX XXXX XXX XXXXXXX XXXXXXXX XX
 XXXXXXXXXXXXXXX XX XXXXXXX XXX X XXXXXXXXXX XXXXXXXX  XXX XXX
 XXX XXXXXX XXXXXXX XXXXXX XXXXXXX XXX XXXX XXXXXXXX

 XXX XXXXXX XXXX XXXXXXXX X XXXX XX XXX XXX XXXXXX XXXXXXX XXXXXX XXXXXXX
 XXXXX XXXX XXXXXXXXXXXXXXXX  XX XXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBBBB
BBBB BBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBB
BBBB BBBB

XXXX XXXXXXXBBBBB BBBBBBBBBBB XXXXXX XXXXXXXXXXXXXXXXBBBBBBBBXX
    BBBBB BBBBBBBBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
    BBBBBBBB

    BBBBB BBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
            BBBBB BBB
                XXX XXXXXXXXXXXXXXXXXXXXXX
                    BBBBB BBBBBBBBB
                        XXX XXXXXXXXXXXXXXX XXXXXXXXXX
                            XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                BBBBB BBBBBBBBBBBBBBBBB gettext(u'catalogue') BBBBBBBB
                            XXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                BBBBBBBBBBBBB BBBBBBB BB BBBBBBBBBBBBBBB
                                XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'whole catalogue') XXXX
                                BB BBBBBBBBBBBBBBB
                                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    BBB BBBBBBBBBBBBB BB BBBBBBBBBBBBBBB
                                        XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                                    BBBBBB
                                BBBBB
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                BBBBB BBBBBBBBBBBBBBBBBBBBBBBB
                                    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBXX gettext(u'Offers') XXXX
                                BBBBBBBB
                            XXXXXX
                        XXXXX
                   BBBBBBBB
               XXXXX
            BBBBBBBB

        XXXXXX
    BBBBBBBB
XXXXXX