BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBBBBB BBBBBBBB BBBBBBB
 XXXX XXXX XX XXXX XX XXXXXXXXXXXXXXX
 XXXXXXXXX XXX XXXX XXXXXXXXXX XXXXX XXXXX XXXX XXXXXXXXX XXXXX XXX

 XXXXXXXXXXXXXXX XX XXXX XXXXXXXXX XXX XXX XXXXXXXXXXXX XX XXXXXX XXXXXX
 XX XXXXX XXX XXXXX XX XXX XXX XXXXXX XXXXXXX XXXXXX XXXXXXX XX
 XXXXXXXXX XX XXX XXXX XXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXX X XX XXX
 XXXXXXXX XX XXX XXXX XXXXXXX XXX XXXXX XXXXXXXX

 XXXXXXXXXXXXXXX XX XXXXXXXXXXX XX XXX XXXX XXXX XX XXXX XX XXXXXXX
 XXX XXXXXXX XXX XXXXXXXXX XXXXXXX XXXX XXX XXXXXXX XXXXXXXX XX
 XXXXXXXXXXXXXXX XX XXXXXXX XXX X XXXXXXXXXX XXXXXXXX  XXX XXX
 XXX XXXXXX XXXXXXX XXXXXX XXXXXXX XXX XXXX XXXXXXXX

 XXX XXXXXX XXXX XXXXXXXX X XXXX XX XXX XXX XXXXXX XXXXXXX XXXXXX XXXXXXX
 XXXXX XXXX XXXXXXXXXXXXXXXX  XX XXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBB
    XXXX XXXX XXXXXX XXXXXXXX XXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBXBBB BBBX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XX
BBBBBBBB

BBBBB BBBBBB
    
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

    
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                
                BBBBB BBBBBBBBBBB
                    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                BBBBBBBB
            XXXXXX
        XXXXXX
        BBBBB BBBBBBBBBB
        
        BBBBBBBB
    XXXXXXXXX

    
    BBBBB BBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                BBBBB BBBBBBBBBBBBBBBBBBB
                BBBBB BBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXXX
                        XXXXBBBBB BBBBBBBBBBBBBBBBBBXXXXX
                    XXXXXX
                BBBBBBBB
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                BBBBB BBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXX
                    BBBBB BBBBBBBBBBBBBBBBB BBBBBBBBB

                    
                    XXXX XXXXXXXXXXXXXXXXXXXBBBBB BBBBBBBBBBBBBBBXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    BBBBBBBB

    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB
